# Skin samples and Midgut Samples Analysis

  # Remove duplicate column causing QIIME2 Error
meta2 <- meta %>%
  select(-SAMPLE_TYPE, -X)
  write.table(meta2, file = './spinyT3_metadata_fixed.txt', col.names = TRUE,
            row.names = FALSE, quote = FALSE, sep = "\t")

  # Upload edited metadata to server 
scp ./spinyT3_metadata_fixed.txt root@10.19.139.174:/data/SpinyT3Samples

  ## Metadata-based filtering
  # In skin_samples_only directory
qiime feature-table filter-samples \
  --i-table /data/SpinyT3Samples/table_spinyT3-no-mitochondria-no-chloroplast-no-unassigned.qza \
  --m-metadata-file /data/SpinyT3Samples/spinyT3_metadata_fixed.txt\
  --p-where "sample_type='skin'" \
  --o-filtered-table table-no-mitochondria-no-chloroplast-no-unassigned-skin-only.qza

  # In midgut_samples_only directory
qiime feature-table filter-samples \
  --i-table /data/SpinyT3Samples/table_spinyT3-no-mitochondria-no-chloroplast-no-unassigned.qza \
  --m-metadata-file /data/SpinyT3Samples/spinyT3_metadata_fixed.txt\
  --p-where "sample_type='midgut'" \
  --o-filtered-table table-no-mitochondria-no-chloroplast-no-unassigned-midgut-only.qza

  # Alpha-rarefaction  
  # Skin only (in screen "skin")
qiime diversity alpha-rarefaction \
    --i-table table-no-mitochondria-no-chloroplast-no-unassigned-skin-only.qza \
    --i-phylogeny /data/SpinyT3Samples/rooted-tree-SpinyT3.qza \
    --p-max-depth 4395 \
    --m-metadata-file /data/SpinyT3Samples/spinyT3_metadata_fixed.txt \
    --o-visualization alpha-rarefaction_skin.qzv

  # Midgut only Alpha-rarefaction (in screen "midgut")
qiime diversity alpha-rarefaction \
    --i-table table-no-mitochondria-no-chloroplast-no-unassigned-midgut-only.qza \
    --i-phylogeny /data/SpinyT3Samples/rooted-tree-SpinyT3.qza \
    --p-max-depth 4395 \
    --m-metadata-file /data/SpinyT3Samples/spinyT3_metadata_fixed.txt \
    --o-visualization alpha-rarefaction_midgut.qzv

  # Calculate alpha- and beta-diversity metrics
  # Skin samples only
qiime diversity core-metrics-phylogenetic \
  --i-phylogeny /data/SpinyT3Samples/rooted-tree-SpinyT3.qza \
  --i-table /data/SpinyT3Samples/skin_samples_only/table-no-mitochondria-no-chloroplast-no-unassigned-skin-only.qza \
  --p-sampling-depth 4395 \
  --m-metadata-file /data/SpinyT3Samples/spinyT3_metadata_fixed.txt \
  --output-dir /data/SpinyT3Samples/skin_samples_only/core-metrics-results-skin

  # Midgut samples only 
qiime diversity core-metrics-phylogenetic \
  --i-phylogeny /data/SpinyT3Samples/rooted-tree-SpinyT3.qza \
  --i-table /data/SpinyT3Samples/midgut_samples_only/table-no-mitochondria-no-chloroplast-no-unassigned-midgut-only.qza \
  --p-sampling-depth 4395 \
  --m-metadata-file /data/SpinyT3Samples/spinyT3_metadata_fixed.txt \
  --output-dir /data/SpinyT3Samples/midgut_samples_only/core-metrics-results-midgut

 # Alpha group significance
 # skin samples only
  qiime diversity alpha-group-significance \
  --i-alpha-diversity /data/SpinyT3Samples/skin_samples_only/core-metrics-results-skin/faith_pd_vector.qza \
  --m-metadata-file /data/SpinyT3Samples/spinyT3_metadata_fixed.txt \
  --o-visualization /data/SpinyT3Samples/skin_samples_only/core-metrics-results-skin/faith-pd-group-significance-skin.qzv

qiime diversity alpha-group-significance \
  --i-alpha-diversity /data/SpinyT3Samples/skin_samples_only/core-metrics-results-skin/shannon_vector.qza \
  --m-metadata-file /data/SpinyT3Samples/spinyT3_metadata_fixed.txt \
  --o-visualization /data/SpinyT3Samples/skin_samples_only/core-metrics-results-skin/shannon-group-significance-skin.qzv

  # midgut samples only
  qiime diversity alpha-group-significance \
  --i-alpha-diversity /data/SpinyT3Samples/midgut_samples_only/core-metrics-results-midgut/faith_pd_vector.qza \
  --m-metadata-file /data/SpinyT3Samples/spinyT3_metadata_fixed.txt \
  --o-visualization /data/SpinyT3Samples/midgut_samples_only/core-metrics-results-midgut/faith-pd-group-significance-midgut.qzv

qiime diversity alpha-group-significance \
  --i-alpha-diversity /data/SpinyT3Samples/midgut_samples_only/core-metrics-results-midgut/shannon_vector.qza \
  --m-metadata-file /data/SpinyT3Samples/spinyT3_metadata_fixed.txt \
  --o-visualization /data/SpinyT3Samples/midgut_samples_only/core-metrics-results-midgut/shannon-group-significance-midgut.qzv

# Calculate beta-group-significance
  # Skin samples only
qiime diversity beta-group-significance \
  --i-distance-matrix /data/SpinyT3Samples/skin_samples_only/core-metrics-results-skin/weighted_unifrac_distance_matrix.qza \
  --m-metadata-file /data/SpinyT3Samples/spinyT3_metadata_fixed.txt \
  --m-metadata-column substrata_collection \
  --o-visualization /data/SpinyT3Samples/skin_samples_only/core-metrics-results-skin/weighted-unifrac-substrata_collection-significance-skin.qzv \
  --p-pairwise

  # Midgut samples only
qiime diversity beta-group-significance \
  --i-distance-matrix /data/SpinyT3Samples/midgut_samples_only/core-metrics-results-midgut/weighted_unifrac_distance_matrix.qza \
  --m-metadata-file /data/SpinyT3Samples/spinyT3_metadata_fixed.txt \
  --m-metadata-column substrata_collection \
  --o-visualization /data/SpinyT3Samples/midgut_samples_only/core-metrics-results-midgut/weighted-unifrac-substrata_collection-significance-midgut.qzv \
  --p-pairwise